theme: jekyll-theme-cayman

title: ithinkmfallin
description: falling forward | thriving 

npage-img: "/img/wakemeupinthesky.jpg
share-links-active:
  twitter: true
  facebook: true
  google: false
  linkedin: true
